name: Deploy Blackjack Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'corretto'
        cache: maven

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image
      run: docker build -t blackjack .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push to Docker Hub
      run: |
        docker tag blackjack ${{ secrets.DOCKER_HUB_USERNAME }}/blackjack:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/blackjack:latest
